# Generated by Django 4.2.7 on 2024-06-07 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("payments", models.DecimalField(decimal_places=2, max_digits=8)),
                ("next_visit", models.DateTimeField(blank=True, null=True)),
                ("spended_time", models.CharField(max_length=10)),
                ("notes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="VisitTreatmentDone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="VisitXray",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="visits.visit"
                    ),
                ),
            ],
        ),
    ]
