# Generated by Django 4.2.7 on 2024-06-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0010_alter_patient_create_date"),
        ("examination", "0003_initial"),
        ("xray", "0001_initial"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitxray",
            name="xray",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="xray.xray"
            ),
        ),
        migrations.AddField(
            model_name="visittreatmentdone",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="examination.patientproblem",
            ),
        ),
        migrations.AddField(
            model_name="visittreatmentdone",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="visits.visit"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="dentist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.doctor"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.employee"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.patient"
            ),
        ),
    ]
