# Generated by Django 4.2.7 on 2024-06-07 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PatientProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_description", models.TextField()),
                ("default_cost", models.DecimalField(decimal_places=2, max_digits=6)),
                ("is_up", models.BooleanField(default=False)),
                ("is_child", models.BooleanField(default=False)),
                ("addtional_treatment", models.TextField()),
                ("is_treated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Teeth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProblemNeededMatrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "matrial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.matrialtype",
                    ),
                ),
                (
                    "treatment_done",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination.patientproblem",
                    ),
                ),
            ],
        ),
    ]
