# Generated by Django 4.2.7 on 2024-06-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("treatment", "0001_initial"),
        ("examination", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientproblem",
            name="defaultTreatment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_patient_problems",
                to="treatment.treatmenttype",
            ),
        ),
        migrations.AddField(
            model_name="patientproblem",
            name="examination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="examination.examination",
            ),
        ),
        migrations.AddField(
            model_name="patientproblem",
            name="teeth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="examination.teeth"
            ),
        ),
        migrations.AddField(
            model_name="patientproblem",
            name="treatment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_problems",
                to="treatment.treatmenttype",
            ),
        ),
    ]
