# Generated by Django 4.2.7 on 2024-06-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("examination", "0002_initial"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="visits.visit"
            ),
        ),
    ]
