# Generated by Django 4.2.7 on 2024-05-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='email',
        ),
    ]
