# Generated by Django 4.2.7 on 2024-06-01 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_rename_user_doctor_email_rename_user_employee_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="create_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_examined",
            field=models.BooleanField(default=False),
        ),
    ]
