# Generated by Django 4.2.7 on 2024-06-01 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_patientfamily_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientfamily",
            name="note",
        ),
    ]
