# Generated by Django 4.2.7 on 2024-06-02 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_patientfamily_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="email",
            new_name="emp_email",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="email",
            new_name="doc_email",
        ),
    ]
