# Generated by Django 4.2.7 on 2024-06-02 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_rename_email_doctor_emp_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="emp_email",
            new_name="doc_email",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="doc_email",
            new_name="emp_email",
        ),
    ]
