# Generated by Django 4.2.7 on 2024-06-02 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_doctor_doc_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_email",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="doctor",
            ),
        ),
    ]
