# Generated by Django 4.2.7 on 2024-06-04 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_employee_emp_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
