# Generated by Django 4.2.7 on 2024-06-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_employee_emp_email"),
        ("anamnesis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anamnesis",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.patient",
            ),
        ),
    ]
